// Code generated by Kitex v0.9.1. DO NOT EDIT.

package commentservice

import (
	comments "HuaTug.com/kitex_gen/comments"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateComment(ctx context.Context, req *comments.CreateCommentRequest, callOptions ...callopt.Option) (r *comments.CreateCommentResponse, err error)
	ListComment(ctx context.Context, req *comments.ListCommentRequest, callOptions ...callopt.Option) (r *comments.ListCommentResponse, err error)
	DeleteComment(ctx context.Context, req *comments.CommentDeleteRequest, callOptions ...callopt.Option) (r *comments.CommentDeleteResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kCommentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCommentServiceClient struct {
	*kClient
}

func (p *kCommentServiceClient) CreateComment(ctx context.Context, req *comments.CreateCommentRequest, callOptions ...callopt.Option) (r *comments.CreateCommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateComment(ctx, req)
}

func (p *kCommentServiceClient) ListComment(ctx context.Context, req *comments.ListCommentRequest, callOptions ...callopt.Option) (r *comments.ListCommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListComment(ctx, req)
}

func (p *kCommentServiceClient) DeleteComment(ctx context.Context, req *comments.CommentDeleteRequest, callOptions ...callopt.Option) (r *comments.CommentDeleteResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteComment(ctx, req)
}
